### ISSUE TITLE
BLE-receiver

### ISSUE THREAD

**Issue by lgs001elite** [NessieCircuits/Riotee_SDK#15]
Hi Kai,

I do not find any API or functions to receive packets on  BLE. Do I need to write a function or call the nordic API directly?

**Comment by geissdoerfer** [comment]
As stated in the [docs](https://www.riotee.nessie-circuits.de/docs/latest/networking/ble.html) Riotee only supports sending BLE advertisements. You can not easily use the Nordic or Zephyr stack as they have a long list of dependencies and are not intermittent-safe.

If you need bidirectional communication, I'd start to experiment with [Stella](https://www.riotee.nessie-circuits.de/docs/latest/networking/stella.html) because it already supports receiving packets.
